AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TripdataRawCrawlerName:
    Type: String
    Default: yellow_tripdata-raw-1
  TripdataCleanedCrawlerName:
    Type: String
    Default: yellow_tripdata-cleaned-1
  TripdataDatabaseName:
    Type: String
    Default: yellow_tripdata-1
  TripdataTablePrefixName:
    Type: String
    Default: yellow_tripdata_
Resources:
  RidesS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
  YellowTripdataDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref TripdataDatabaseName
        Description: "AWS Glue container to hold metadata tables for the rides crawler"
  YellowRidesRawCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref TripdataRawCrawlerName
      Role: !GetAtt GlueRole.Arn
      Description: AWS Glue crawler to crawl raw data
      DatabaseName: !Ref TripdataDatabaseName
      Targets:
        S3Targets:
          - Path: !Join
              - ''
              - - 's3://'
                - !Ref RidesS3Bucket
                - '/raw'
      TablePrefix: !Ref TripdataTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
  YellowRidesCleanedCrawlerFlights:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref TripdataCleanedCrawlerName
      Role: !GetAtt GlueRole.Arn
      Description: AWS Glue crawler to crawl cleaned data
      DatabaseName: !Ref TripdataDatabaseName
      Targets:
        S3Targets:
          - Path: !Join
              - ''
              - - 's3://'
                - !Ref RidesS3Bucket
                - '/cleaned'
      TablePrefix: !Ref TripdataTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
Outputs:
  RidesS3Bucket:
    Value: !Ref RidesS3Bucket
    Export:
      Name: RidesS3Bucket
